### PR TITLE
Fix BT21-024 do not show placed card & update for current standards

### LINKED ISSUE #1253: BT21-024 Cyberdramon
Effect for opponent to place card from hand to sec is revealing that card and at least putting it in top left log.

### PR DESCRIPTION
**Pull request by hooperk**

### CODE REVIEW

File: CardEffect/BT21/Red/BT21_024.cs [hunk 1]
```diff
@@ -10,161 +10,98 @@ public override List<ICardEffect> CardEffects(EffectTiming timing, CardSource ca
...
+                        isShowOpponent: false,
+                        selectCardCoroutine: SelectCardCoroutine,
+                        afterSelectCardCoroutine: null,
+                        mode: SelectHandEffect.Mode.Custom,
+                        cardEffect: activateClass);
+
+                    selectHandEffect.SetUpCustomMessage(
+                        "Select 1 card to place at the bottom of security.",
+                        "The opponent is selecting 1 card to place at the bottom of security.");
+                    selectHandEffect.SetNotShowCard(true);
```
Comment (hooperk) [inline CardEffect/BT21/Red/BT21_024.cs:49]: This line is the bug fix, the rest was reworking to our shared method format

**Review by x89rt2 — APPROVED** [review]
